# Generated by Django 6.0.5 on 2026-07-11 16:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def cap_existing_coupon_amounts(apps, schema_editor):
    Coupon = apps.get_model('cafe_app', 'Coupon')
    Coupon.objects.filter(amount__gt=Decimal('2500.00')).update(amount=Decimal('2500.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0003_customerprofile_review'),
    ]

    operations = [
        migrations.RunPython(cap_existing_coupon_amounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('2500.00'))]),
        ),
    ]
