# Generated by Django 6.0.6 on 2026-07-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0005_coupon_usage_limit_coupon_used_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='free_coffee_rewards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='reward_points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='membership',
            field=models.CharField(choices=[('regular', 'Regular'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='regular', max_length=20),
        ),
    ]
